# Generated by Django 5.2.1 on 2025-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_post_tweet_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
